### ISSUE TITLE
Practica 7 Juicio experto

### ISSUE THREAD

**Issue by EdwinOrtiz1412** [SistemasTecTlaxiaco/actividad-7-juicio-experto-y-costos-entrevista_equipo-irving#3]
[Practica 7_Juicio Experto y costos.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-juicio-experto-y-costos-entrevista_equipo-irving/files/13190896/Practica.7_Juicio.Experto.y.costos.pdf)

**Comment by bg55-a** [comment]
calif: 30%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
